name: CI
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
jobs:
  build:
    runs-on: macOS-latest
    steps:
      uses: actions/checkout@v1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
    - name: Build and run tests
      env:
        DISCORD_WEB_HOOK: ${{ secrets.DISCORD_WEB_HOOK }}
      run: |
        bundle exec fastlane build_and_test
        bundle exec fastlane discord_success