name: CI
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  test:
    # Job name is Test
    name: Test
    # This job runs on macOS
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: Dependencies
        run: |
          bundle exec pod install
      - name: Build and test
        run: |
          bundle exec fastlane say_hi
      - name: Notify if failure
        env:
          DISCORD_WEB_HOOK: ${{ secrets.DISCORD_WEB_HOOK }}
        run: |
          bundle exec fastlane discord_failure
      - name: Notify if success
        env:
          DISCORD_WEB_HOOK: ${{ secrets.DISCORD_WEB_HOOK }}
        run: |
          bundle exec fastlane discord_success